
version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    user: root
    restart: always
    ports:
     - "8990:8080"
    volumes: 
      - ./localdata:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins
    restart: always
